stages:
  - test
  - build
  - test2
  - dev
  - stage
  - prod

instal_env:
  stage: test
  scripts:
    - echo " test 1 "

run_test:
  stage: test
  scripts:
    - echo " test 2 "

linters:
  stage: test
  scripts:
    - echo " test linter "

build:
  stage: build
  scripts:
    - ./build.sh
  when: manual

test_after_build:
  stage: test2
  scripts:
    - echo " test after build "

deploy_dev:
  stage: dev
  scripts:
    - echo " running ./build.sh "
  when: manual

deploy_stage:
  stage: stage
  scripts:
    - ./deploy.sh
  when: manual
  only:
    refs:
      -tags
      -master

deploy_prod:
  stage: pro
  scripts:
    - echo " running ./deploy.sh "
  when: manual
  only:
    refs:
      -tags
      -master
